workflows:
  main:
    name: Main Workflow
    environment:
      vars:
        # Environment variables and configurations

    # Configuration for iOS builds
    ios:
      xcode_workspace: ios/Runner.xcworkspace
      xcode_scheme: Runner
      export_method: ad-hoc
      include_bitcode: false
      output_directory: build
      artifacts:
        - build/**/*.ipa

    # Configuration for Android builds
    android:
      flavors:
        - flavor1
        - flavor2
      build_modes:
        - release
      output_directory: build/app/outputs/apk/release
      artifacts:
        - build/app/outputs/**/*.apk

    # Scripts or commands to run after the build
    scripts:
      - flutter test
      - flutter build web

    # Notifications configuration
    notifications:
      email:
        recipients:
          - example1@example.com
          - example2@example.com
        on_success: always
        on_failure: always
      slack:
        webhook_url: https://hooks.slack.com/services/ABC12345/XYZ98765/your-slack-webhook-url
        on_success: always
        on_failure: always
