name: socialv_prokit
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_vector_icons: ^2.0.0
  
  # APIs
  html: ^0.15.4
  http: ^1.1.0
  intl: ^0.18.1

  # Images
  image_picker: ^1.0.0

  # Others
  cached_network_image: ^3.2.3
  dots_indicator: ^3.0.0
  nb_utils: ^6.0.0
  package_info_plus: ^4.0.2
  google_fonts: ^5.1.0
  otp_text_field: ^1.1.3
  fl_chart: ^0.63.0
  scan: ^1.6.0

  # State Management
  flutter_mobx: ^2.0.6+5

  # Story
  flutter_reaction_button: ^2.0.1+2
  story_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.8
  mobx_codegen: ^2.0.5+2

    #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - images/socialv/posts/
    - images/socialv/faces/ 
    - images/socialv/
    - images/socialv/icons/
    - images/socialv/gifs/
    - images/theme12/
    - images/walletApp/
